WebShop/Models/ErrorViewModel.cs
namespace WebShop.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebShop/Controllers/AboutController.cs
using Business.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace WebShop.Controllers
{
	public class AboutController : Controller
	{
		private readonly IAboutService _aboutService;

		public AboutController(IAboutService aboutService)
		{
			_aboutService = aboutService;
		}

		public IActionResult Index()
		{
			var values = _aboutService.GetAll();
			return View(values);
		}
	}
}

WebShop/Controllers/AdminController.cs
using Business.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace WebShop.Controllers
{
    public class AdminController : Controller
    {
        private readonly IProductService _productService;

        public AdminController(IProductService productService)
        {
            _productService = productService;
        }

        public IActionResult Index()
        {
            return View();
        }

        //Product
        public IActionResult ProductIndex()
        {
            var values = _productService.GetAll();
            return View(values.OrderByDescending(x=>x.ID));
        }
    }
}

WebShop/Controllers/ContactController.cs
using Business.Abstract;
using DTO.DTOEntity;
using Microsoft.AspNetCore.Mvc;

namespace WebShop.Controllers
{
	public class ContactController : Controller
	{
		private readonly IContactService _contactService;
		private readonly IMessageService _messageService;

		public ContactController(IContactService contactService, IMessageService messageService)
		{
			_contactService = contactService;
			_messageService = messageService;
		}

		[HttpGet]
		public IActionResult Index()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Index(MessageDTO p)
		{
			p.CreateDate= DateTime.Now;	
			_messageService.Insert(p);
			return RedirectToAction("Index","Home");
		}
	}
}

WebShop/Controllers/HomeController.cs
using Business.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace WebShop.Controllers
{
    public class HomeController : Controller
    {
        private readonly IProductService _productService;

        public HomeController(IProductService productService)
        {
            _productService = productService;
        }

        public IActionResult Index()
        {
            var values = _productService.GetAll();
            return View(values.OrderByDescending(x=>x.ID));
        }
    }
}

WebShop/Controllers/LoginController.cs
using DTO.DTOEntity;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Business.Abstract;
using Microsoft.AspNetCore.Http.HttpResults;

namespace WebShop.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUserService _userService;

        public LoginController(IUserService userService)
        {
            _userService = userService;
        }

        [HttpGet]
        public IActionResult SignIn()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SignIn(UserDTO p)
        {
            var user = _userService.Login(p);
            Authenticate(user);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SignUp(UserDTO p)
		{
            p.ImageURL = "admin.jpg";
            p.Create = DateTime.Now;
            _userService.Insert(p);
            return RedirectToAction("SignIn", "Login");
        }

        [HttpGet]
        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("SignIn", "Login");
        }

        //Cookie
        private void Authenticate(UserDTO user)
        {
            var claims = new List<Claim>
            {
                new Claim("Id", user.ID.ToString()),
                new Claim("UserName", user.UserName),
                new Claim(ClaimTypes.Role, user.RoleName),
            };

            ClaimsIdentity id = new ClaimsIdentity(claims, "ApplicationCookie");

            HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(id));
        }
    }
}

WebShop/Controllers/SearchController.cs
using Business.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace WebShop.Controllers
{
	public class SearchController : Controller
	{
		private readonly IProductService _productService;

		public SearchController(IProductService productService)
		{
			_productService = productService;
		}

		public IActionResult Index(string product)
		{
			var values = from p in _productService.GetAll() select p;
			if (!string.IsNullOrEmpty(product))
			{
				values = values.Where(x => x.Title.ToLower().Contains(product.ToLower())); ;
			}
			return View(values.OrderByDescending(x => x.ID));
		}
	}
}

WebShop/Views/About/Index.cshtml
@model IEnumerable<DTO.DTOEntity.AboutDTO>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_PageLayout.cshtml";
}

<div class="sub-banner">
</div>
<div class="about">
	<div class="container">
		<h3>About Us</h3>
		<div class="about-info">
			@foreach (var item in Model)
			{
				<div class="col-md-8 about-grids">
					<h4>@item.Title</h4>
					<p>@item.Description</p>
					<div class="about-w3ls-row">
						<script type="text/javascript">
							$(window).load(function () {
								$("#flexiselDemo3").flexisel({
									visibleItems: 2,
									animationSpeed: 1000,
									autoPlay: false,
									autoPlaySpeed: 3000,
									pauseOnHover: true,
									enableResponsiveBreakpoints: true,
									responsiveBreakpoints: {
										portrait: {
											changePoint: 480,
											visibleItems: 2
										},
										landscape: {
											changePoint: 640,
											visibleItems: 2
										},
										tablet: {
											changePoint: 768,
											visibleItems: 2
										}
									}
								});

							});
						</script>
						<script type="text/javascript" src="~/WebTema/js/jquery.flexisel.js"></script>
						<ul id="flexiselDemo3">
							<li>
								<img src="@item.Image" class="img-responsive" alt="" />
							</li>
							<li>
								<img src="~/WebTema/images/a2.jpg" class="img-responsive" alt="" />
							</li>
							<li>
								<img src="~/WebTema/images/a3.jpg" class="img-responsive" alt="" />
							</li>
							<li>
								<img src="~/WebTema/images/a4.jpg" class="img-responsive" alt="" />
							</li>
						</ul>
						<div class="clearfix"> </div>
					</div>
				</div>
			}
			<div class="col-md-4 about-grids">
				<h4>Our Advantages</h4>
				<div class="pince">
					<div class="pince-left">
						<h5>01</h5>
					</div>
					<div class="pince-right">
						<p>Vero vulputate enim non justo posuere phasellus eget  mauris.</p>
					</div>
					<div class="clearfix"> </div>
				</div>
				<div class="pince">
					<div class="pince-left">
						<h5>02</h5>
					</div>
					<div class="pince-right">
						<p>Vero vulputate enim non justo posuere phasellus eget  mauris.</p>
					</div>
					<div class="clearfix"> </div>
				</div>
				<div class="pince">
					<div class="pince-left">
						<h5>03</h5>
					</div>
					<div class="pince-right">
						<p>Vero vulputate enim non justo posuere phasellus eget  mauris.</p>
					</div>
					<div class="clearfix"> </div>
				</div>
				<div class="pince">
					<div class="pince-left">
						<h5>04</h5>
					</div>
					<div class="pince-right">
						<p>Vero vulputate enim non justo posuere phasellus eget  mauris.</p>
					</div>
					<div class="clearfix"> </div>
				</div>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
</div>

WebShop/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section id="main-content">
	<section class="wrapper">
		<!-- //market-->
		<div class="market-updates">
			<div class="col-md-3 market-update-gd">
				<div class="market-update-block clr-block-2">
					<div class="col-md-4 market-update-right">
						<i class="fa fa-eye"> </i>
					</div>
					<div class="col-md-8 market-update-left">
						<h4>Visitors</h4>
						<h3>13,500</h3>
						<p>Other hand, we denounce</p>
					</div>
					<div class="clearfix"> </div>
				</div>
			</div>
			<div class="col-md-3 market-update-gd">
				<div class="market-update-block clr-block-1">
					<div class="col-md-4 market-update-right">
						<i class="fa fa-users"></i>
					</div>
					<div class="col-md-8 market-update-left">
						<h4>Users</h4>
						<h3>1,250</h3>
						<p>Other hand, we denounce</p>
					</div>
					<div class="clearfix"> </div>
				</div>
			</div>
			<div class="col-md-3 market-update-gd">
				<div class="market-update-block clr-block-3">
					<div class="col-md-4 market-update-right">
						<i class="fa fa-usd"></i>
					</div>
					<div class="col-md-8 market-update-left">
						<h4>Sales</h4>
						<h3>1,500</h3>
						<p>Other hand, we denounce</p>
					</div>
					<div class="clearfix"> </div>
				</div>
			</div>
			<div class="col-md-3 market-update-gd">
				<div class="market-update-block clr-block-4">
					<div class="col-md-4 market-update-right">
						<i class="fa fa-shopping-cart" aria-hidden="true"></i>
					</div>
					<div class="col-md-8 market-update-left">
						<h4>Orders</h4>
						<h3>1,500</h3>
						<p>Other hand, we denounce</p>
					</div>
					<div class="clearfix"> </div>
				</div>
			</div>
			<div class="clearfix"> </div>
		</div>
		<!-- //market-->
		<div class="row">
			<div class="panel-body">
				<div class="col-md-12 w3ls-graph">
					<!--agileinfo-grap-->
					<div class="agileinfo-grap">
						<div class="agileits-box">
							<header class="agileits-box-header clearfix">
								<h3>Visitor Statistics</h3>
								<div class="toolbar">
								</div>
							</header>
							<div class="agileits-box-body clearfix">
								<div id="hero-area"></div>
							</div>
						</div>
					</div>
					<!--//agileinfo-grap-->

				</div>
			</div>
		</div>
		<div class="agil-info-calendar">
			<!-- calendar -->
			<div class="col-md-6 agile-calendar">
				<div class="calendar-widget">
					<div class="panel-heading ui-sortable-handle">
						<span class="panel-icon">
							<i class="fa fa-calendar-o"></i>
						</span>
						<span class="panel-title"> Calendar Widget</span>
					</div>
					<!-- grids -->
					<div class="agile-calendar-grid">
						<div class="page">

							<div class="w3l-calendar-left">
								<div class="calendar-heading">
								</div>
								<div class="monthly" id="mycalendar"></div>
							</div>

							<div class="clearfix"> </div>
						</div>
					</div>
				</div>
			</div>
			<!-- //calendar -->
			<div class="col-md-6 w3agile-notifications">
				<div class="notifications">
					<!--notification start-->

					<header class="panel-heading">
						Notification
					</header>
					<div class="notify-w3ls">
						<div class="alert alert-info clearfix">
							<span class="alert-icon"><i class="fa fa-envelope-o"></i></span>
							<div class="notification-info">
								<ul class="clearfix notification-meta">
									<li class="pull-left notification-sender"><span><a href="#">Jonathan Smith</a></span> send you a mail </li>
									<li class="pull-right notification-time">1 min ago</li>
								</ul>
								<p>
									Urgent meeting for next proposal
								</p>
							</div>
						</div>
						<div class="alert alert-danger">
							<span class="alert-icon"><i class="fa fa-facebook"></i></span>
							<div class="notification-info">
								<ul class="clearfix notification-meta">
									<li class="pull-left notification-sender"><span><a href="#">Jonathan Smith</a></span> mentioned you in a post </li>
									<li class="pull-right notification-time">7 Hours Ago</li>
								</ul>
								<p>
									Very cool photo jack
								</p>
							</div>
						</div>
						<div class="alert alert-success ">
							<span class="alert-icon"><i class="fa fa-comments-o"></i></span>
							<div class="notification-info">
								<ul class="clearfix notification-meta">
									<li class="pull-left notification-sender">You have 5 message unread</li>
									<li class="pull-right notification-time">1 min ago</li>
								</ul>
								<p>
									<a href="#">Anjelina Mewlo, Jack Flip</a> and <a href="#">3 others</a>
								</p>
							</div>
						</div>
						<div class="alert alert-warning ">
							<span class="alert-icon"><i class="fa fa-bell-o"></i></span>
							<div class="notification-info">
								<ul class="clearfix notification-meta">
									<li class="pull-left notification-sender">Domain Renew Deadline 7 days ahead</li>
									<li class="pull-right notification-time">5 Days Ago</li>
								</ul>
								<p>
									Next 5 July Thursday is the last day
								</p>
							</div>
						</div>
						<div class="alert alert-info clearfix">
							<span class="alert-icon"><i class="fa fa-envelope-o"></i></span>
							<div class="notification-info">
								<ul class="clearfix notification-meta">
									<li class="pull-left notification-sender"><span><a href="#">Jonathan Smith</a></span> send you a mail </li>
									<li class="pull-right notification-time">1 min ago</li>
								</ul>
								<p>
									Urgent meeting for next proposal
								</p>
							</div>
						</div>

					</div>

					<!--notification end-->
				</div>
			</div>
			<div class="clearfix"> </div>
		</div>
		<!-- tasks -->
		<div class="agile-last-grids">
			<div class="col-md-4 agile-last-left">
				<div class="agile-last-grid">
					<div class="area-grids-heading">
						<h3>Monthly</h3>
					</div>
					<div id="graph7"></div>
					<script>
						// This crosses a DST boundary in the UK.
						Morris.Area({
							element: 'graph7',
							data: [
								{ x: '2013-03-30 22:00:00', y: 3, z: 3 },
								{ x: '2013-03-31 00:00:00', y: 2, z: 0 },
								{ x: '2013-03-31 02:00:00', y: 0, z: 2 },
								{ x: '2013-03-31 04:00:00', y: 4, z: 4 }
							],
							xkey: 'x',
							ykeys: ['y', 'z'],
							labels: ['Y', 'Z']
						});
					</script>

				</div>
			</div>
			<div class="col-md-4 agile-last-left agile-last-middle">
				<div class="agile-last-grid">
					<div class="area-grids-heading">
						<h3>Daily</h3>
					</div>
					<div id="graph8"></div>
					<script>
						/* data stolen from http://howmanyleft.co.uk/vehicle/jaguar_'e'_type */
						var day_data = [
							{ "period": "2016-10-01", "licensed": 3407, "sorned": 660 },
							{ "period": "2016-09-30", "licensed": 3351, "sorned": 629 },
							{ "period": "2016-09-29", "licensed": 3269, "sorned": 618 },
							{ "period": "2016-09-20", "licensed": 3246, "sorned": 661 },
							{ "period": "2016-09-19", "licensed": 3257, "sorned": 667 },
							{ "period": "2016-09-18", "licensed": 3248, "sorned": 627 },
							{ "period": "2016-09-17", "licensed": 3171, "sorned": 660 },
							{ "period": "2016-09-16", "licensed": 3171, "sorned": 676 },
							{ "period": "2016-09-15", "licensed": 3201, "sorned": 656 },
							{ "period": "2016-09-10", "licensed": 3215, "sorned": 622 }
						];
						Morris.Bar({
							element: 'graph8',
							data: day_data,
							xkey: 'period',
							ykeys: ['licensed', 'sorned'],
							labels: ['Licensed', 'SORN'],
							xLabelAngle: 60
						});
					</script>
				</div>
			</div>
			<div class="col-md-4 agile-last-left agile-last-right">
				<div class="agile-last-grid">
					<div class="area-grids-heading">
						<h3>Yearly</h3>
					</div>
					<div id="graph9"></div>
					<script>
						var day_data = [
							{ "elapsed": "I", "value": 34 },
							{ "elapsed": "II", "value": 24 },
							{ "elapsed": "III", "value": 3 },
							{ "elapsed": "IV", "value": 12 },
							{ "elapsed": "V", "value": 13 },
							{ "elapsed": "VI", "value": 22 },
							{ "elapsed": "VII", "value": 5 },
							{ "elapsed": "VIII", "value": 26 },
							{ "elapsed": "IX", "value": 12 },
							{ "elapsed": "X", "value": 19 }
						];
						Morris.Line({
							element: 'graph9',
							data: day_data,
							xkey: 'elapsed',
							ykeys: ['value'],
							labels: ['value'],
							parseTime: false
						});
					</script>

				</div>
			</div>
			<div class="clearfix"> </div>
		</div>
		<!-- //tasks -->
		<div class="agileits-w3layouts-stats">
			<div class="col-md-4 stats-info widget">
				<div class="stats-info-agileits">
					<div class="stats-title">
						<h4 class="title">Browser Stats</h4>
					</div>
					<div class="stats-body">
						<ul class="list-unstyled">
							<li>
								GoogleChrome <span class="pull-right">85%</span>
								<div class="progress progress-striped active progress-right">
									<div class="bar green" style="width:85%;"></div>
								</div>
							</li>
							<li>
								Firefox <span class="pull-right">35%</span>
								<div class="progress progress-striped active progress-right">
									<div class="bar yellow" style="width:35%;"></div>
								</div>
							</li>
							<li>
								Internet Explorer <span class="pull-right">78%</span>
								<div class="progress progress-striped active progress-right">
									<div class="bar red" style="width:78%;"></div>
								</div>
							</li>
							<li>
								Safari <span class="pull-right">50%</span>
								<div class="progress progress-striped active progress-right">
									<div class="bar blue" style="width:50%;"></div>
								</div>
							</li>
							<li>
								Opera <span class="pull-right">80%</span>
								<div class="progress progress-striped active progress-right">
									<div class="bar light-blue" style="width:80%;"></div>
								</div>
							</li>
							<li class="last">
								Others <span class="pull-right">60%</span>
								<div class="progress progress-striped active progress-right">
									<div class="bar orange" style="width:60%;"></div>
								</div>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="col-md-8 stats-info stats-last widget-shadow">
				<div class="stats-last-agile">
					<table class="table stats-table ">
						<thead>
							<tr>
								<th>S.NO</th>
								<th>PRODUCT</th>
								<th>STATUS</th>
								<th>PROGRESS</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<th scope="row">1</th>
								<td>Lorem ipsum</td>
								<td><span class="label label-success">In progress</span></td>
								<td><h5>85% <i class="fa fa-level-up"></i></h5></td>
							</tr>
							<tr>
								<th scope="row">2</th>
								<td>Aliquam</td>
								<td><span class="label label-warning">New</span></td>
								<td><h5>35% <i class="fa fa-level-up"></i></h5></td>
							</tr>
							<tr>
								<th scope="row">3</th>
								<td>Lorem ipsum</td>
								<td><span class="label label-danger">Overdue</span></td>
								<td><h5 class="down">40% <i class="fa fa-level-down"></i></h5></td>
							</tr>
							<tr>
								<th scope="row">4</th>
								<td>Aliquam</td>
								<td><span class="label label-info">Out of stock</span></td>
								<td><h5>100% <i class="fa fa-level-up"></i></h5></td>
							</tr>
							<tr>
								<th scope="row">5</th>
								<td>Lorem ipsum</td>
								<td><span class="label label-success">In progress</span></td>
								<td><h5 class="down">10% <i class="fa fa-level-down"></i></h5></td>
							</tr>
							<tr>
								<th scope="row">6</th>
								<td>Aliquam</td>
								<td><span class="label label-warning">New</span></td>
								<td><h5>38% <i class="fa fa-level-up"></i></h5></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div class="clearfix"> </div>
		</div>
	</section>
	<!-- footer -->
	<div class="footer">
		<div class="wthree-copyright">
			<p>© 2017 Visitors. All rights reserved | Design by <a href="http://w3layouts.com">W3layouts</a></p>
		</div>
	</div>
	<!-- / footer -->
</section>

WebShop/Views/Contact/Index.cshtml
@model DTO.DTOEntity.MessageDTO
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_PageLayout.cshtml";
}

<div class="sub-banner">
</div>
<div class="contact">
	<div class="container">
		<h3>Contact Us</h3>
		@await Component.InvokeAsync("ContactList")
		<div class="col-md-9 col-sm-9 contact-right">
			<form method="post">
				<input type="text" asp-for="Name" placeholder="Your name" required=" ">
				<input type="text" asp-for="Email" placeholder="Your email" required=" ">
				<input type="text" asp-for="Subject" placeholder="Your subject" required=" ">
				<input type="text" asp-for="PhoneNumber" placeholder="Phone number" required=" ">
				<textarea asp-for="Text" placeholder="Your message" required=" "></textarea>
				<input type="submit" value="Send message">
			</form>
		</div>
	</div>
</div>
<div class="map-w3ls">
	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d22702.22744502486!2d11.113366067229226!3d44.662878362361056!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x477fc3eca9065c15%3A0x12ec8a03aadae866!2s40019+Sant&#39;Agata+Bolognese+BO%2C+Italy!5e0!3m2!1sen!2sin!4v1451281303075" allowfullscreen></iframe>
</div>

WebShop/Views/Partial/FooterPartial.cshtml
<!-- top-brands -->
<div class="top-brands">
	<div class="container">
		<h3>Top Brands</h3>
		<div class="sliderfig">
			<ul id="flexiselDemo1">
				<li>
					<img src="~/WebTema/images/4.png" alt=" " class="img-responsive" />
				</li>
				<li>
					<img src="~/WebTema/images/5.png" alt=" " class="img-responsive" />
				</li>
				<li>
					<img src="~/WebTema/images/6.png" alt=" " class="img-responsive" />
				</li>
				<li>
					<img src="~/WebTema/images/7.png" alt=" " class="img-responsive" />
				</li>
				<li>
					<img src="~/WebTema/images/46.jpg" alt=" " class="img-responsive" />
				</li>
			</ul>
		</div>
		<script type="text/javascript">
			$(window).load(function () {
				$("#flexiselDemo1").flexisel({
					visibleItems: 4,
					animationSpeed: 1000,
					autoPlay: false,
					autoPlaySpeed: 3000,
					pauseOnHover: true,
					enableResponsiveBreakpoints: true,
					responsiveBreakpoints: {
						portrait: {
							changePoint: 480,
							visibleItems: 1
						},
						landscape: {
							changePoint: 640,
							visibleItems: 2
						},
						tablet: {
							changePoint: 768,
							visibleItems: 3
						}
					}
				});

			});
		</script>
		<script type="text/javascript" src="~/WebTema/js/jquery.flexisel.js"></script>
	</div>
</div>
<!-- //top-brands -->
<!-- //newsletter -->
<div class="footer">
	<div class="container">
		<div class="col-md-3 footer-grids fgd1">
			<a href="index.html"><img src="~/WebTema/images/logo2.png" alt=" " /><h3>FASHION<span>CLUB</span></h3></a>
			<ul>
				<li>Laçın Ticarət Mərkəzi,</li>
				<li>Bakı şəhəri.</li>
				<li><a href="mailto:info@example.com">info@example.com</a></li>
				<a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
				<a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a>
				<a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
				<a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
			</ul>
		</div>
		<div class="col-md-3 footer-grids fgd2">
			<h4>Məlumat</h4>
			<ul>
				<li><a asp-controller="Contact" asp-action="Index">Bizimlə əlaqə</a></li>
				<li><a asp-controller="About" asp-action="Index">Xəritə</a></li>
				<li><a href="faq.html">FAQ's</a></li>
			</ul>
		</div>
		<div class="col-md-3 footer-grids fgd3">
			<h4>Mağaza</h4>
			<ul>
				<li><a href="jewellery.html">Cəvahirat</a></li>
				<li><a href="cosmetics.html">Kosmetika</a></li>
				<li><a href="Shoes.html">Ayaqqabı</a></li>
				<li><a href="deos.html">Ətir</a></li>
			</ul>
		</div>
		<div class="col-md-3 footer-grids fgd4">
			<h4>Mənim profilim</h4>
			<ul>

				<li><a asp-controller="Login" asp-action="SignIn">Login</a></li>
				<li><a asp-controller="Login" asp-action="SignUp">Register</a></li>
				<li><a href="recommended.html">Tövsiyyə </a></li>
				<li><a href="payment.html">Ödəniş</a></li>
			</ul>
		</div>
		<div class="clearfix"></div>
		<p class="copy-right">© 2016 Fashion Club . All rights reserved | Design by <a href="http://w3layouts.com"> W3layouts.</a></p>
	</div>
</div>
<!-- cart-js -->
<script src="~/WebTema/js/minicart.js"></script>
<script>
	w3ls1.render();

	w3ls1.cart.on('w3sb1_checkout', function (evt) {
		var items, len, i;

		if (this.subtotal() > 0) {
			items = this.items();

			for (i = 0, len = items.length; i < len; i++) {
				items[i].set('shipping', 0);
				items[i].set('shipping2', 0);
			}
		}
	});
</script>
<!-- //cart-js -->  

WebShop/Views/Partial/NavBarPartial.cshtml
<div class="header-top-w3layouts">
	<div class="container">
		<div class="col-md-6 logo-w3">
			<a asp-controller="Home" asp-action="Index"><img src="~/WebTema/images/logo2.png" alt=" " /><h1>FASHİON<span>CLUB</span>  </h1></a>
		</div>
		<div class="col-md-6 phone-w3l">
			@await Component.InvokeAsync("PhoneList")
		</div>
		<div class="clearfix"></div>
	</div>
</div>
<div class="header-bottom-w3ls">
	<div class="container">
		<div class="col-md-7 navigation-agileits">
			<nav class="navbar navbar-default">
				<div class="navbar-header nav_2">
					<button type="button" class="navbar-toggle collapsed navbar-toggle1" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
				</div>
				<div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
					<ul class="nav navbar-nav ">
						<li class=" active"><a asp-controller="Home" asp-action="Index" class="hyper "><span>Ana səhifə</span></a></li>
						<li><a asp-controller="About" asp-action="Index" class="hyper"><span>Haqqımızda</span></a></li>
						<li><a asp-controller="Contact" asp-action="Index" class="hyper"><span>Bizimlə əlaqə</span></a></li>
						<li><a asp-controller="Login" asp-action="SignIn" class="hyper"><span>Login</span></a></li>
						<li><a asp-controller="Login" asp-action="SignUp"><span>Register</span></a></li>
						@if (User.IsInRole("Admin"))
						{
							<li><a asp-controller="Admin" asp-action="Index" class="hyper"><span>Admin</span></a></li>
						}
					</ul>
				</div>
			</nav>
		</div>
		<script>
			$(document).ready(function () {
				$(".dropdown").hover(
					function () {
						$('.dropdown-menu', this).stop(true, true).slideDown("fast");
						$(this).toggleClass('open');
					},
					function () {
						$('.dropdown-menu', this).stop(true, true).slideUp("fast");
						$(this).toggleClass('open');
					}
				);
			});
		</script>
		<div class="col-md-4 search-agileinfo">
			<form asp-controller="Search" asp-action="Index" method="get">
				<input type="search" name="product" placeholder="Məhsul axtar..." required="">
				<button type="submit" class="btn btn-default search" aria-label="Left Align">
					<i class="fa fa-search" aria-hidden="true"> </i>
				</button>
			</form>
		</div>
		<div class="col-md-1 cart-wthree">
			<div class="cart">
				<form action="#" method="post" class="last">
					<input type="hidden" name="cmd" value="_cart" />
					<input type="hidden" name="display" value="1" />
					<button class="w3view-cart" type="submit" name="submit" value=""><i class="fa fa-cart-arrow-down" aria-hidden="true"></i></button>
				</form>
			</div>
		</div>
		<div class="clearfix"></div>
	</div>
</div>